name: etl pipeline

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run program1
        run: python .github/workflows/program1.py

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run program2
        run: echo "${{ inputs.programmer_name }}" | python .github/workflows/program2.py

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run program3
        run: python .github/workflows/program3.py

  job4:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run program4
        run: python .github/workflows/program4.py

  job5:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run program1
        run: python .github/workflows/program1.py

  job6:
    runs-on: ubuntu-latest
    needs: [job4, job5]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run program1
        run: python .github/workflows/program1.py